name: afrovending

services:
  - name: backend
    source_dir: /backend
    build_command: pip install -r requirements.txt
    run_command: uvicorn server_modular:app --host 0.0.0.0 --port 8080
    http_port: 8080
    routes:
      - path: /api
    envs:
      - key: MONGO_URL
        scope: RUN_TIME
        type: SECRET
      - key: DB_NAME
        scope: RUN_TIME
        value: afrovending_db
      - key: JWT_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: STRIPE_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: SENDGRID_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: SENDER_EMAIL
        scope: RUN_TIME
        value: noreply@afrovending.com
      - key: FRONTEND_URL
        scope: RUN_TIME
        value: https://afrovending.com
      - key: CLOUDINARY_CLOUD_NAME
        scope: RUN_TIME
        value: AfroVending
      - key: CLOUDINARY_API_KEY
        scope: RUN_TIME
        value: "862876839633786"
      - key: CLOUDINARY_API_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: CORS_ORIGINS
        scope: RUN_TIME
        value: "*"

static_sites:
  - name: frontend
    source_dir: /frontend
    build_command: yarn install && yarn build
    output_dir: /build
    routes:
      - path: /
    catchall_document: index.html
    envs:
      - key: REACT_APP_BACKEND_URL
        scope: BUILD_TIME
        value: ""
